# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_commentmodel_likemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
